### ISSUE TITLE
Fix Warning

### ISSUE THREAD

**Issue by SpotInAdmin** [spotin/spotin#117]
![image](https://github.com/spotin/spotin/assets/124765932/0d4a959a-a7a1-40d5-8e5e-bd5029a0d5fd)

**Comment by Nortalle** [comment]
https://jscrambler.com/blog/best-practices-for-secure-session-management-in-node

Is it a good practice to use our own Postgres Database as a store of the session ?
https://www.npmjs.com/package/connect-pg-simple

**Comment by ludelafo** [comment]
Fixed with #127 as it was removed to use `fetch`.
