### ISSUE TITLE
Registration email

### ISSUE THREAD

**Issue by nfriedli** [spotin/spotin#177]
In the login address confirmation e-mail, the link to Spotin is not active. Perhaps because the `https://` protocol is missing, or because it's pure text.

Cf. #174 
![Capture du 2024-09-17 14-02-21](https://github.com/user-attachments/assets/0014f352-1184-46ec-aca6-cfd67f5ace96)

**Comment by Nortalle** [comment]
Corrected in

**Comment by Nortalle** [comment]
Corrected in #174
